### ISSUE TITLE
DYNLIB Issue

### ISSUE THREAD

**Issue by sugarleaf** [OpenOrbis/mira-project-archive#20]

**Comment by CrazyVoidProgrammer** [comment]
I will look in to this and see if i can fix, if i can not, i'll let kiwi know.

**Comment by seb5594** [comment]
I’m pretty sure to have the solution.
The function has been changed abit since fw 4.xx with one params less.
Instead of... int(*sceSysUtilSendSystemNotificationWithText)(int messageType, int userID, char* message)

...try it with the following

int(*sceSysUtilSendSystemNotificationWithText)(int messageType, char* message)

**Comment by CrazyVoidProgrammer** [comment]
@seb5594 the prototype was wrong but was not the issue.

The issues seem to be with dynlib -> sys_dynlib_load_prx

I've tried a dozen different variations of doing dynlib and all fail on the sys_dynlib_load_prx 
So focus should be on why sys_dynlib_load_prx is failing!

**Comment by ghost** [comment]
Fixed in #47
